swagger:
    contact:
        email: 'gleisserctba@hotmail.com'
        name: 'Gleisser Santos'
        url: 'https://github.com/Gleisser'
    description: API gateway to access all microservices endpoints using a single entry point
    license: 'Apache License 2.0'
    licenseUrl: 'https://www.apache.org/licenses/LICENSE-2.0'
    termsOfServiceUrl: 'https://www.apache.org/licenses/LICENSE-2.0'
    title: social-profile-service
    version: 0.1-SNAPSHOT