eureka:
  instance:
    prefer-ip-address: true
    ip-address: "${HOST}" #That`s the eureka instace host that this client have.
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka/ #on this case eureka is located on an external container otherwise change the ip to localhost.
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: social-user-service
        uri: lb://social-user-service
        predicates:
        - Path=/user/**
      - id: social-profile-service
        uri: lb://social-profile-service
        predicates:
        - Path=/profile/**
        
info:
  app:
    name: @project.name@
    version: @project.version@
    decription: @project.version@